CREATE INDEX ix_users_created_at ON users (created_at);

--@block
SHOW INDEXES FROM users;

--@block
SELECT
    TABLE_NAME,
    CONSTRAINT_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_NAME IS NOT NULL
      AND TABLE_SCHEMA = 'blog_db';