"""Added Revoke token table)

Revision ID: 10451e6a96b8
Revises: 1fe108fb1738
Create Date: 2025-04-01 22:24:37.162835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10451e6a96b8'
down_revision: Union[str, None] = '1fe108fb1738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'revoked_tokens',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('token', sa.String(length=255), nullable=False, index=True, unique=True),
        sa.Column('expires', sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
