"""Add tags column to blogs

Revision ID: 654393af47a4
Revises: ad49827942e4
Create Date: 2025-02-10 02:37:32.078770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '654393af47a4'
down_revision: Union[str, None] = 'ad49827942e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blogs", sa.Column("tag", sa.String(255), nullable=True, index=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blogs", sa.Column("tag", sa.String(255), nullable=True, index=True))
    # ### end Alembic commands ###
