"""Follow model created

Revision ID: b2bcbba0841f
Revises: 4cdf17eed85b
Create Date: 2025-01-16 05:02:16.329700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision: str = 'b2bcbba0841f'
down_revision: Union[str, None] = '4cdf17eed85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        conn = op.get_bind()
        if not conn.dialect.has_table(conn, 'follows'):
            op.create_table(
            'follows',
            sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
            sa.Column('follower_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
            sa.Column('followed_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
            sa.Column('created_at', sa.DateTime, nullable=True, default=lambda: datetime.now(timezone.utc)),
            sa.ForeignKeyConstraint(['follower_id'], ['users.id']),
            sa.ForeignKeyConstraint(['followed_id'], ['users.id']),
            mysql_collate='utf8mb4_0900_ai_ci',
            mysql_default_charset='utf8mb4',
            mysql_engine='InnoDB'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='follows_ibfk_2'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_follows_id', 'follows', ['id'], unique=False)
    op.create_index('ix_follows_created_at', 'follows', ['created_at'], unique=False)
    op.create_table('blogs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('published_at', mysql.DATETIME(), nullable=True),
    sa.Column('published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='blogs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_blogs_published_at', 'blogs', ['published_at'], unique=False)
    op.create_index('ix_blogs_published', 'blogs', ['published'], unique=False)
    op.create_index('ix_blogs_id', 'blogs', ['id'], unique=False)
    op.create_index('ix_blogs_created_at', 'blogs', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=255), server_default=sa.text("'author'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
